export const ORDERS_FETCH = "ORDERS_FETCH";
export const ORDER_CREATE = "ORDER_CREATE";

export const PRODUCTS_FETCH = "PRODUCTS_FETCH";
export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
